#!/usr/bin/env python3
"""Copy the files that exist nowhere else.

Two files in data/ are deliberately outside git, and for good reasons:
outreach_prospects.csv is third-party business contact data, sender.env holds
a home postal address, and this repository is public. .gitignore excludes
both, and it should keep excluding both.

The consequence is easy to miss. Everything else in this project exists in at
least three places -- the working copy, GitHub, and whatever Render and
Cloudflare have deployed. These two exist on one disk. No commit history, no
remote, no second copy. The prospect list is the entire sales pipeline and
the record of who has asked never to be contacted again; losing it does not
just lose the leads, it loses the opt-outs, which is the part that cannot be
rebuilt by searching again.

So this copies them somewhere else, dated, and says what it did. Point it at
a folder that syncs off the machine -- OneDrive, Dropbox, an external drive --
because a second copy on the same disk survives a mistake but not a failure.

    python3 tools/backup_local_data.py "C:/Users/Josh/OneDrive/curbcall-backup"
    python3 tools/backup_local_data.py ~/Backups/curbcall --keep 30
    python3 tools/backup_local_data.py ~/Backups/curbcall --list

On Windows, Task Scheduler will run this daily. It is small and it is quiet:
nothing to read unless something is wrong.
"""
import argparse
import datetime
import hashlib
import os
import re
import shutil
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(os.path.dirname(_HERE), "data")

# The gitignored files worth keeping. Anything else in data/ is either in the
# repo already or can be regenerated by the tools that built it.
PRECIOUS = ["outreach_prospects.csv", "sender.env"]

STAMP = re.compile(r"^(\d{4}-\d{2}-\d{2})__")
DEFAULT_KEEP = 60


def _digest(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def backup(dest, today=None):
    """(copied, missing). Verifies each copy rather than trusting the write."""
    today = today or datetime.date.today().isoformat()
    os.makedirs(dest, exist_ok=True)
    copied, missing = [], []
    for name in PRECIOUS:
        src = os.path.join(DATA, name)
        if not os.path.exists(src):
            missing.append(name)
            continue
        out = os.path.join(dest, "%s__%s" % (today, name))
        shutil.copy2(src, out)
        # A backup nobody checked is a backup nobody has.
        if _digest(src) != _digest(out):
            os.unlink(out)
            raise IOError("copy of %s did not verify" % name)
        copied.append(out)
    return copied, missing


def prune(dest, keep_days, today=None):
    """Delete dated copies older than keep_days. Never touches anything
    it did not name itself -- the stamp prefix is the whole permission."""
    today = today or datetime.date.today()
    if isinstance(today, str):
        today = datetime.date.fromisoformat(today)
    removed = []
    for name in sorted(os.listdir(dest)):
        m = STAMP.match(name)
        if not m:
            continue
        try:
            when = datetime.date.fromisoformat(m.group(1))
        except ValueError:
            continue
        if (today - when).days > keep_days:
            os.unlink(os.path.join(dest, name))
            removed.append(name)
    return removed


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dest", help="folder to copy into; use a synced one")
    ap.add_argument("--keep", type=int, default=DEFAULT_KEEP,
                    help="days of history to retain (default %d)" % DEFAULT_KEEP)
    ap.add_argument("--list", action="store_true",
                    help="show what is already backed up and stop")
    args = ap.parse_args()

    if args.list:
        if not os.path.isdir(args.dest):
            print("no backups at %s" % args.dest, file=sys.stderr)
            return 1
        names = [n for n in sorted(os.listdir(args.dest)) if STAMP.match(n)]
        for n in names:
            print(n)
        print("\n%d file(s). Newest: %s" % (len(names),
                                            names[-1] if names else "none"))
        return 0

    copied, missing = backup(args.dest)
    for path in copied:
        print("saved %s" % path)
    for name in missing:
        # Not an error. sender.env is absent on any machine that has never
        # sent outreach, and saying so is more use than a stack trace.
        print("not on this machine: %s" % name, file=sys.stderr)
    removed = prune(args.dest, args.keep)
    if removed:
        print("pruned %d copy(ies) older than %d days"
              % (len(removed), args.keep))
    if not copied:
        print("nothing was backed up", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
